/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restauranteitson_PresentacionCU5_ManejoClientes;

import restauranteitson_PresentacionCU3_GestionIngredientes.*;
import restauranteitson_BusinessLogic_Fabrica.FabricaObjetoNegocio;
import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;
import restauranteitson_PresentacionMENU.MenuPrincipalJFrame;

/**
 *
 * @author abrilislas
 */
public class CU5_PantallaRegistroExitoso extends javax.swing.JFrame {

    /**
     * Creates new form MenuCU3_GestionIngredientes
     */
    //private iIngredientesBO ingredientesBO;
   // private static final Logger LOG = Logger.getLogger(RegistroVideojuego.class.getName());
        
    public CU5_PantallaRegistroExitoso() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionUnidadMedida = new javax.swing.ButtonGroup();
        pnlRoot = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        pnlLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAceptarSalirMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(854, 542));

        pnlRoot.setBackground(new java.awt.Color(75, 90, 228));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlBotones.setBackground(new java.awt.Color(75, 90, 228));

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        pnlRoot.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlLabel.setBackground(new java.awt.Color(75, 90, 228));

        jLabel1.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Se ha registrado un nuevo cliente.");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnAceptarSalirMenu.setBackground(new java.awt.Color(75, 90, 228));
        btnAceptarSalirMenu.setFont(new java.awt.Font("InaiMathi", 1, 24)); // NOI18N
        btnAceptarSalirMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarSalirMenu.setText("¡Excelente!");
        btnAceptarSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarSalirMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLabelLayout = new javax.swing.GroupLayout(pnlLabel);
        pnlLabel.setLayout(pnlLabelLayout);
        pnlLabelLayout.setHorizontalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarSalirMenu))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        pnlLabelLayout.setVerticalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAceptarSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlRoot.add(pnlLabel, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAceptarSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarSalirMenuActionPerformed
        dispose();
        MenuPrincipalJFrame menu = new MenuPrincipalJFrame();
        menu.setVisible(true);
    }//GEN-LAST:event_btnAceptarSalirMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CU5_PantallaRegistroExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CU5_PantallaRegistroExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CU5_PantallaRegistroExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CU5_PantallaRegistroExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new CU3_RegistrarIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SeleccionUnidadMedida;
    private javax.swing.JButton btnAceptarSalirMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlLabel;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
