/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restauranteitson_PresentacionCU5_ManejoClientes;

import java.awt.BorderLayout;
import restauranteitson_BusinessLogic_Interfaces.IClientesBO;
import restauranteitson_Presentacion_RecursosGenerales.JPanelBusqueda;
import restauranteitson_Presentacion_RecursosGenerales.JFrameBase;
import restauranteitson_dominio.ClienteFrecuente;

/**
 *
 * @author abrilislas
 */
public class CU5_GenerarReporteInicio extends JFrameBase {

    /**
     * Creates new form MenuCU3_GestionIngredientes
     */
  // private iIngredientesBO ingredientesBO;
   // private static final Logger LOG = Logger.getLogger(RegistroVideojuego.class.getName());
    IClientesBO clienteBO;
    ClienteFrecuente cliente;
    int casoUso=5;
    
    public CU5_GenerarReporteInicio(IClientesBO clienteBO) {
        super();
        initComponents(); // Initialize the GUI components.
        this.clienteBO=clienteBO;
        JPanelBusqueda panelBusqueda = new JPanelBusqueda(casoUso,clienteBO); //recibe como parametro el 
                                                            // numero de CU que lo invoca
        pnlFiltro.add(panelBusqueda,BorderLayout.CENTER);
        pnlFiltro.revalidate();  // Recalcula el diseño
        pnlFiltro.repaint();     // Redibuja el panel
        
    }
    //Constructor para crear ventana con un ingrediente seleccionado
     public CU5_GenerarReporteInicio(ClienteFrecuente cliente, IClientesBO clienteBO) {
        super();
        initComponents(); // Initialize the GUI components.
        this.clienteBO=clienteBO;
        this.cliente=cliente;
        JPanelBusqueda panelBusqueda = new JPanelBusqueda(casoUso,clienteBO); //recibe como parametro el 
                                                            // numero de CU que lo invoca
        pnlFiltro.add(panelBusqueda,BorderLayout.CENTER);
        pnlFiltro.revalidate();  // Recalcula el diseño
        pnlFiltro.repaint();     // Redibuja el panel
        labelNombreCliente.setText(cliente.getNombreCliente());
        clienteField.setText(cliente.getNombreCliente());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionUnidadMedida = new javax.swing.ButtonGroup();
        pnlRoot = new javax.swing.JPanel();
        pnlFiltro = new javax.swing.JPanel();
        pnlContenido = new javax.swing.JPanel();
        labelNombreCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numeroVisitasField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        btnSalirMenu3 = new javax.swing.JButton();
        clienteField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(854, 542));

        pnlRoot.setBackground(new java.awt.Color(225, 225, 246));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlFiltro.setPreferredSize(new java.awt.Dimension(854, 120));
        pnlFiltro.setLayout(new java.awt.BorderLayout());
        pnlRoot.add(pnlFiltro, java.awt.BorderLayout.PAGE_START);

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));

        labelNombreCliente.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 24)); // NOI18N
        labelNombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        labelNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreCliente.setText("Selecciona un cliente...");
        labelNombreCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 90, 228));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Filtrar");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel6.setFont(new java.awt.Font("Hiragino Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Número de visitas:");

        numeroVisitasField.setForeground(new java.awt.Color(102, 102, 102));
        numeroVisitasField.setText("00");

        jLabel5.setFont(new java.awt.Font("Hiragino Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Cliente:");

        btnGenerarReporte.setBackground(new java.awt.Color(75, 90, 228));
        btnGenerarReporte.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(225, 225, 246));
        btnGenerarReporte.setText("Generar");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        btnSalirMenu3.setBackground(new java.awt.Color(51, 51, 51));
        btnSalirMenu3.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnSalirMenu3.setForeground(new java.awt.Color(225, 225, 246));
        btnSalirMenu3.setText("Salir");

        clienteField.setForeground(new java.awt.Color(102, 102, 102));
        clienteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 90, 228));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Generar reporte ");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(numeroVisitasField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(clienteField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirMenu3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(labelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 118, Short.MAX_VALUE))
            .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                    .addContainerGap(10, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(labelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroVisitasField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalirMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlContenidoLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(312, Short.MAX_VALUE)))
        );

        pnlRoot.add(pnlContenido, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        dispose();
        CU5_VisualizarReporte pantallaVisualizarReporte = new CU5_VisualizarReporte();
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void clienteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CU5_GenerarReporteInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CU5_GenerarReporteInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CU5_GenerarReporteInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CU5_GenerarReporteInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new CU3_RegistrarIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SeleccionUnidadMedida;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnSalirMenu;
    private javax.swing.JButton btnSalirMenu1;
    private javax.swing.JButton btnSalirMenu2;
    private javax.swing.JButton btnSalirMenu3;
    private javax.swing.JTextField clienteField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JTextField numeroVisitasField;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlFiltro;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
