/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restauranteitson_Presentacion_RecursosGenerales;

import restauranteitson_enum.UnidadIngrediente;

/**
 *
 * @author abrilislas
 */
public class JPanelConsultarIngredientes extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConsultarIngredientes
     * @param nombreIngrediente
     */
    public JPanelConsultarIngredientes(String nombreIngrediente,UnidadIngrediente unidadMedida,Integer stock){
        initComponents();
        labelNombreIngrediente.setText(nombreIngrediente);
        labelUnidadMedida.setText(unidadMedida.toString());
        labelStock.setText(stock.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        labelNombreIngrediente = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        labelStockActual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelUnidadMedida = new javax.swing.JLabel();
        btnRegistrarNuevoCliente = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        labelNombreIngrediente.setFont(new java.awt.Font("K2D", 1, 18)); // NOI18N
        labelNombreIngrediente.setText("NombreIngredientePlaceholder");

        labelStock.setForeground(new java.awt.Color(102, 102, 102));
        labelStock.setText("Stock actual:");

        labelStockActual.setText("00");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Unidad de medida:");

        labelUnidadMedida.setText("unidadPlaceholder");

        btnRegistrarNuevoCliente.setBackground(new java.awt.Color(75, 90, 228));
        btnRegistrarNuevoCliente.setFont(new java.awt.Font("InaiMathi", 1, 14)); // NOI18N
        btnRegistrarNuevoCliente.setForeground(new java.awt.Color(225, 225, 246));
        btnRegistrarNuevoCliente.setText("Seleccionar");
        btnRegistrarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNuevoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUnidadMedida))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(labelStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelStockActual))
                            .addComponent(labelNombreIngrediente))
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarNuevoCliente)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(labelNombreIngrediente)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelStockActual)
                            .addComponent(labelStock)))
                    .addComponent(btnRegistrarNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUnidadMedida)
                    .addComponent(jLabel3))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(pnlPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoClienteActionPerformed
        //construye un dto del ingrediente
    }//GEN-LAST:event_btnRegistrarNuevoClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarNuevoCliente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelNombreIngrediente;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelStockActual;
    private javax.swing.JLabel labelUnidadMedida;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
