/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restauranteitson_Presentacion_RecursosGenerales;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restauranteitson_BusinessLogic_Exepciones.NegocioException;
import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;
import restauranteitson_dominio.Ingrediente;

/**
 *
 * @author abrilislas
 */
public class JPanelBusqueda extends javax.swing.JPanel {
    /**
     * Creates new form JPanelBusqueda
     */
    private int CUInvocador;
    
    public JPanelBusqueda(int CUInvocador){
        initComponents();
        this.CUInvocador = CUInvocador;
    }
    /*
        public String[] generarColumnas(int CUInvocador){

        switch(CUInvocador){
            
            case 1: //Buscar ingrediente
                JFrameTablaBusquedaIngredientes frameBusqueda = new JFrameTablaBusquedaIngredientes();
                 
            case 2: //Buscar platillo
               return new String[] {"ID", "Nombre", "Precio", "Tipo"};
            case 3: //Buscar cliente
               return new String[] {"ID", "Nombre", "Correo"};
            default: //buscar cliente
                return new String[] {"ID", "Nombre", "Correo"};
            } 
        }
 
   public void generarTablaIngredientes(iIngredientesBO ingredientesBO, String[] columnas){
    try {
        String filtro = buscar();
        List<Ingrediente> ingredientes = this.ingredientesBO.consultarIngredientes(filtro);
        DefaultTableModel model = new DefaultTableModel(columnas, 0);
        DefaultTableModel modeloTabla = (DefaultTableModel) JFrameTablaBusqueda.getFrames(),.getModel();
        modeloTabla.setRowCount(0); // Limpiar cualquier dato previo en la tabla
        
        // Iteramos sobre la lista de ingredientes y agregamos a la tabla
        for (Ingrediente ingrediente : ingredientes) {
            Object[] fila = {
                ingrediente.getId(),      
                ingrediente.getNombreIngrediente(),  
                ingrediente.getUnidadMedida(), 
                ingrediente.getStock()    
            };
            
            
            modeloTabla.addRow(fila); // Añadir la fila a la tabla
        }
        
    } catch (NegocioException e) {
        // Manejar excepciones (puedes mostrar un mensaje de error o similar)
        JOptionPane.showMessageDialog(null, "Error al consultar los ingredientes: " + e.getMessage());
    }
}

    
    public String buscar(){
       String filtroBusquedaTexto = filtroBusqueda.getText();
       return filtroBusquedaTexto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        filtroBusqueda = new javax.swing.JTextField();
        btnBuscarFiltroBusqueda = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        filtroBusqueda.setBackground(new java.awt.Color(241, 241, 241));
        filtroBusqueda.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        filtroBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        filtroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroBusquedaActionPerformed(evt);
            }
        });

        btnBuscarFiltroBusqueda.setBackground(new java.awt.Color(75, 90, 228));
        btnBuscarFiltroBusqueda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBuscarFiltroBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarFiltroBusqueda.setText("Buscar");
        btnBuscarFiltroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFiltroBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(filtroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnBuscarFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filtroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnBuscarFiltroBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filtroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroBusquedaActionPerformed

    private void btnBuscarFiltroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFiltroBusquedaActionPerformed
        //generarColumnas(int CUInvocador);
    }//GEN-LAST:event_btnBuscarFiltroBusquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFiltroBusqueda;
    private javax.swing.JTextField filtroBusqueda;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
