/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restauranteitson_Presentacion_RecursosGenerales;

import java.text.SimpleDateFormat;
import restauranteitson_BusinessLogic_Fabrica.FabricaObjetoNegocio;
import restauranteitson_BusinessLogic_Interfaces.IClientesBO;
import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;
import restauranteitson_PresentacionCU3_GestionIngredientes.CU3_ActualizarStock;
import restauranteitson_PresentacionCU5_ManejoClientes.CU5_GenerarReporteInicio;
import restauranteitson_dominio.ClienteFrecuente;

/**
 *
 * @author abrilislas
 */
public class JPanelConsultarClientes extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConsultarIngredientes
     * @param nombreIngrediente
     */
    private IClientesBO clienteBO;
    private JFrameTablaBusqueda framePadre;
    private ClienteFrecuente cliente;
    public JPanelConsultarClientes(ClienteFrecuente cliente, JFrameTablaBusqueda framePadre){
        initComponents();
        this.framePadre = framePadre;
        this.cliente=cliente;
        //Configuracion de date
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
        String fechaFormateada = formato.format(cliente.getFechaRegistro().getTime());
        
        //Actualizamos labels 
        labelNombreCliente.setText(cliente.getNombreCliente());
        labelFechaRegistro.setText(fechaFormateada);        
        labeEmail.setText(cliente.getCorreo());
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        labelNombreCliente = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        labeEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelFechaRegistro = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(418, 126));
        setLayout(new java.awt.BorderLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));

        labelNombreCliente.setFont(new java.awt.Font("K2D", 1, 18)); // NOI18N
        labelNombreCliente.setText("NombreClientePlaceholder");

        labelStock.setForeground(new java.awt.Color(102, 102, 102));
        labelStock.setText("Email:");

        labeEmail.setText("Sin registrar");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Fecha de registro");

        labelFechaRegistro.setText("unidadPlaceholder");

        btnSeleccionar.setBackground(new java.awt.Color(75, 90, 228));
        btnSeleccionar.setFont(new java.awt.Font("InaiMathi", 1, 24)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(225, 225, 246));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFechaRegistro)
                        .addContainerGap(365, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(labelStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeEmail))
                            .addComponent(labelNombreCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar)
                        .addGap(22, 22, 22))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(labelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStock)
                            .addComponent(labeEmail))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFechaRegistro)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(pnlPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        framePadre.dispose();

        // Creamos y mostramos CU3_ActualizarStock con el ingrediente seleccionado
        IClientesBO clientesBO = FabricaObjetoNegocio.crearClienteBO();
        CU5_GenerarReporteInicio frameActualizar = new CU5_GenerarReporteInicio(cliente, clientesBO);
        frameActualizar.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labeEmail;
    private javax.swing.JLabel labelFechaRegistro;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JLabel labelStock;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
