/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restauranteitson_Presentacion_RecursosGenerales;

import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;
import restauranteitson_Presentacion_RecursosGenerales.JFrameTablaBusqueda;

/**
 *
 * @author abrilislas
/**
 *
 * @author abrilislas
 */
public class JPanelBusqueda extends javax.swing.JPanel {
    /**
     * Creates new form JPanelBusqueda
     */
    private int CUInvocador;
    iIngredientesBO ingredientesBO;
    
    public JPanelBusqueda(int CUInvocador, iIngredientesBO ingredientesBO){
        initComponents();
        this.CUInvocador = CUInvocador;
        this.ingredientesBO=ingredientesBO;
        this.setVisible(true);
    }
    
    public void buscar(){
        String filtroBusquedaTexto = filtroBusqueda.getText();
        JFrameTablaBusqueda nuevoFrameTablaBusqueda = new JFrameTablaBusqueda(CUInvocador,filtroBusquedaTexto,ingredientesBO);
        nuevoFrameTablaBusqueda.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        filtroBusqueda = new javax.swing.JTextField();
        btnBuscarFiltroBusqueda = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        setMaximumSize(new java.awt.Dimension(300, 60));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(854, 120));
        setSize(new java.awt.Dimension(300, 60));

        filtroBusqueda.setBackground(new java.awt.Color(241, 241, 241));
        filtroBusqueda.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        filtroBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        filtroBusqueda.setPreferredSize(new java.awt.Dimension(300, 60));
        filtroBusqueda.setSize(new java.awt.Dimension(300, 60));
        filtroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroBusquedaActionPerformed(evt);
            }
        });

        btnBuscarFiltroBusqueda.setBackground(new java.awt.Color(102, 102, 255));
        btnBuscarFiltroBusqueda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBuscarFiltroBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarFiltroBusqueda.setText("Buscar");
        btnBuscarFiltroBusqueda.setPreferredSize(new java.awt.Dimension(300, 60));
        btnBuscarFiltroBusqueda.setSize(new java.awt.Dimension(300, 60));
        btnBuscarFiltroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFiltroBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(filtroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnBuscarFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filtroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroBusquedaActionPerformed

    private void btnBuscarFiltroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFiltroBusquedaActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarFiltroBusquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFiltroBusqueda;
    private javax.swing.JTextField filtroBusqueda;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
