/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restauranteitson_Presentacion_RecursosGenerales;

import restauranteitson_BusinessLogic_Fabrica.FabricaObjetoNegocio;
import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;
import restauranteitson_PresentacionCU3_GestionIngredientes.CU3_ActualizarStock;
import restauranteitson_dominio.Ingrediente;

/**
 *
 * @author abrilislas
 */
public class JPanelConsultarIngredientes extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConsultarIngredientes
     * @param nombreIngrediente
     */
    private Ingrediente ingrediente;
    private JFrameTablaBusqueda framePadre;
    private iIngredientesBO ingredienteBO;
    public JPanelConsultarIngredientes(Ingrediente ingrediente, JFrameTablaBusqueda framePadre){
        initComponents();
        this.framePadre = framePadre;

        this.ingrediente=ingrediente;
        //Actualizamos labels 
        labelNombreIngrediente.setText(ingrediente.getNombreIngrediente());
        labelUnidadMedida.setText(ingrediente.getUnidadMedida().toString());
        labelStockActual.setText(ingrediente.getStock().toString());
        setVisible(true);
    }
    public CU3_ActualizarStock obtenerIngrediente(){
        iIngredientesBO ingredientesBO = FabricaObjetoNegocio.crearIngredienteBO();
        return new CU3_ActualizarStock(ingrediente, ingredientesBO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        labelNombreIngrediente = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        labelStockActual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelUnidadMedida = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(418, 126));
        setLayout(new java.awt.BorderLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));

        labelNombreIngrediente.setFont(new java.awt.Font("K2D", 1, 18)); // NOI18N
        labelNombreIngrediente.setText("NombreIngredientePlaceholder");

        labelStock.setForeground(new java.awt.Color(102, 102, 102));
        labelStock.setText("Stock actual:");

        labelStockActual.setText("00");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Unidad de medida:");

        labelUnidadMedida.setText("unidadPlaceholder");

        btnSeleccionar.setBackground(new java.awt.Color(75, 90, 228));
        btnSeleccionar.setFont(new java.awt.Font("InaiMathi", 1, 24)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(225, 225, 246));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUnidadMedida)
                        .addContainerGap(353, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(labelStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelStockActual))
                            .addComponent(labelNombreIngrediente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar)
                        .addGap(22, 22, 22))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(labelNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelStockActual)
                            .addComponent(labelStock))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUnidadMedida)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(pnlPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        framePadre.dispose();

        // Creamos y mostramos CU3_ActualizarStock con el ingrediente seleccionado
        iIngredientesBO ingredientesBO = FabricaObjetoNegocio.crearIngredienteBO();
        CU3_ActualizarStock frameActualizar = new CU3_ActualizarStock(ingrediente, ingredientesBO);
        frameActualizar.setVisible(true);

    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelNombreIngrediente;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelStockActual;
    private javax.swing.JLabel labelUnidadMedida;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
