/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restauranteitson_Presentacion_RecursosGenerales;

import restauranteitson_BusinessLogic_Fabrica.FabricaObjetoNegocio;
import restauranteitson_BusinessLogic_Interfaces.IProductosBO;
import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;
import restauranteitson_PresentacionCU3_GestionIngredientes.CU3_ActualizarStock;
import restauranteitson_dominio.Ingrediente;
import restauranteitson_dominio.Producto;

/**
 *
 * @author abrilislas
 */
public class JPanelConsultarProductos extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConsultarIngredientes
     * @param nombreIngrediente
     */
    private Producto producto;
    private JFrameTablaBusqueda framePadre;
    private IProductosBO productoBO;
    public JPanelConsultarProductos(Producto producto, JFrameTablaBusqueda framePadre){
        initComponents();
        this.framePadre = framePadre;
        this.producto=producto;
        //Actualizamos labels 
        labelProducto.setText(producto.getNombreProducto());
        labelTipo.setText(producto.getTipo().toString());
        labelPrecio.setText(producto.getPrecio().toString());
        setVisible(true);
    }
  /*  public CU3_ActualizarStock obtenerIngrediente(){
        iIngredientesBO ingredientesBO = FabricaObjetoNegocio.crearIngredienteBO();
        return //new CU3_ActualizarStock(producto, productoBO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        labelProducto = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(418, 126));
        setLayout(new java.awt.BorderLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));

        labelProducto.setFont(new java.awt.Font("K2D", 1, 18)); // NOI18N
        labelProducto.setText("NombreProdcutoPlaceholder");

        labelStock.setForeground(new java.awt.Color(102, 102, 102));
        labelStock.setText("Precio");

        labelPrecio.setText("00.00");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Tipo:");

        labelTipo.setText("tipoPlaceholder");

        btnSeleccionar.setBackground(new java.awt.Color(75, 90, 228));
        btnSeleccionar.setFont(new java.awt.Font("InaiMathi", 1, 24)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(225, 225, 246));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTipo)
                        .addContainerGap(455, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(labelStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPrecio))
                            .addComponent(labelProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar)
                        .addGap(22, 22, 22))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(labelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStock)
                            .addComponent(labelPrecio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipo)
                    .addComponent(jLabel3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(pnlPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        framePadre.dispose();

        // Creamos y mostramos CU3_ActualizarStock con el ingrediente seleccionado
        iIngredientesBO ingredientesBO = FabricaObjetoNegocio.crearIngredienteBO();
      //  CU3_ActualizarStock frameActualizar = new CU3_ActualizarStock(ingrediente, ingredientesBO);
      //  frameActualizar.setVisible(true);

    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelProducto;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
