/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restauranteitson_PresentacionCU3_GestionIngredientes;

import java.awt.BorderLayout;
import restauranteitson_Presentacion_RecursosGenerales.JPanelBusqueda;
import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;
import restauranteitson_PresentacionMENU.MenuPrincipalJFrame;
import restauranteitson_Presentacion_RecursosGenerales.JFrameBase;
import restauranteitson_dominio.Ingrediente;

/**
 *
 * @author abrilislas
 */
public class CU3_ActualizarStock extends JFrameBase {

    /**
     * Creates new form MenuCU3_GestionIngredientes
     */
  // private iIngredientesBO ingredientesBO;
   // private static final Logger LOG = Logger.getLogger(RegistroVideojuego.class.getName());
    iIngredientesBO ingredientesBO;
    Ingrediente ingrediente;
    int casoUso=3;
    
    public CU3_ActualizarStock(iIngredientesBO ingredientesBO) {
        super();
        initComponents(); // Initialize the GUI components.
        this.ingredientesBO=ingredientesBO;
        JPanelBusqueda panelBusqueda = new JPanelBusqueda(casoUso,ingredientesBO); //recibe como parametro el 
                                                            // numero de CU que lo invoca
        pnlFiltro.add(panelBusqueda,BorderLayout.CENTER);
        pnlFiltro.revalidate();  // Recalcula el diseño
        pnlFiltro.repaint();     // Redibuja el panel
        
    }
    //Constructor para crear ventana con un ingrediente seleccionado
     public CU3_ActualizarStock(Ingrediente ingrediente, iIngredientesBO ingredientesBO) {
        initComponents(); // Initialize the GUI components.
        this.ingredientesBO=ingredientesBO;
        this.ingrediente=ingrediente;
        JPanelBusqueda panelBusqueda = new JPanelBusqueda(casoUso,ingredientesBO); //recibe como parametro el 
                                                            // numero de CU que lo invoca
        pnlFiltro.add(panelBusqueda,BorderLayout.CENTER);
        pnlFiltro.revalidate();  // Recalcula el diseño
        pnlFiltro.repaint();     // Redibuja el panel
        labelNombreIngrediente.setText(ingrediente.getNombreIngrediente());
        labelStockActual.setText(ingrediente.getStock().toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionUnidadMedida = new javax.swing.ButtonGroup();
        pnlRoot = new javax.swing.JPanel();
        pnlFiltro = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnSalirMenu = new javax.swing.JButton();
        btnActualizarStock = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        labelNombreIngrediente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textField_NombreIngrediente = new javax.swing.JTextField();
        labelStockActual = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(854, 542));
        setResizable(false);
        setSize(new java.awt.Dimension(854, 542));

        pnlRoot.setBackground(new java.awt.Color(225, 225, 246));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlFiltro.setPreferredSize(new java.awt.Dimension(854, 120));
        pnlFiltro.setLayout(new java.awt.BorderLayout());
        pnlRoot.add(pnlFiltro, java.awt.BorderLayout.PAGE_START);

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnSalirMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnSalirMenu.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnSalirMenu.setForeground(new java.awt.Color(225, 225, 246));
        btnSalirMenu.setText("Salir");
        btnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuActionPerformed(evt);
            }
        });

        btnActualizarStock.setBackground(new java.awt.Color(75, 90, 228));
        btnActualizarStock.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnActualizarStock.setForeground(new java.awt.Color(225, 225, 246));
        btnActualizarStock.setText("Actualizar");
        btnActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(btnActualizarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));

        labelNombreIngrediente.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 24)); // NOI18N
        labelNombreIngrediente.setForeground(new java.awt.Color(102, 102, 102));
        labelNombreIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreIngrediente.setText("Selecciona un ingrediente...");
        labelNombreIngrediente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 90, 228));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar inventario");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Hiragino Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Agregar:");

        textField_NombreIngrediente.setForeground(new java.awt.Color(204, 204, 204));
        textField_NombreIngrediente.setText("00");

        labelStockActual.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        labelStockActual.setForeground(new java.awt.Color(153, 0, 51));
        labelStockActual.setText("00");

        jLabel5.setFont(new java.awt.Font("Hiragino Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Stock actual:");

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStockActual)
                .addGap(118, 118, 118)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField_NombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(labelNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textField_NombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStockActual)
                    .addComponent(jLabel5))
                .addGap(66, 66, 66))
        );

        pnlRoot.add(pnlContenido, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarStockActionPerformed
        ingrediente.setStock(ingrediente.getStock()+Integer.parseInt(labelStockActual.getText()));
    }//GEN-LAST:event_btnActualizarStockActionPerformed

    private void btnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuActionPerformed
        dispose();
        MenuPrincipalJFrame menu = new MenuPrincipalJFrame();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSalirMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CU3_ActualizarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CU3_ActualizarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CU3_ActualizarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CU3_ActualizarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new CU3_RegistrarIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SeleccionUnidadMedida;
    private javax.swing.JButton btnActualizarStock;
    private javax.swing.JButton btnSalirMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelNombreIngrediente;
    private javax.swing.JLabel labelStockActual;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlFiltro;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JTextField textField_NombreIngrediente;
    // End of variables declaration//GEN-END:variables
}
