/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restauranteitson_PresentacionCU3_GestionIngredientes;

import restauranteitson_BusinessLogic_Fabrica.FabricaObjetoNegocio;
import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;
import restauranteitson_PresentacionMENU.MenuPrincipalJFrame;

/**
 *
 * @author abrilislas
 */
public class CU3_PantallaRegistroExitoso extends javax.swing.JFrame {

    /**
     * Creates new form MenuCU3_GestionIngredientes
     */
    //private iIngredientesBO ingredientesBO;
   // private static final Logger LOG = Logger.getLogger(RegistroVideojuego.class.getName());
        
    public CU3_PantallaRegistroExitoso() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionUnidadMedida = new javax.swing.ButtonGroup();
        pnlRoot = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnAceptarSalirMenu = new javax.swing.JButton();
        btnActualizarStock = new javax.swing.JButton();
        btnRegresarRegistroIngrediente = new javax.swing.JButton();
        pnlLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(854, 542));

        pnlRoot.setBackground(new java.awt.Color(225, 225, 246));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlBotones.setBackground(new java.awt.Color(225, 225, 246));

        btnAceptarSalirMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnAceptarSalirMenu.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnAceptarSalirMenu.setForeground(new java.awt.Color(225, 225, 246));
        btnAceptarSalirMenu.setText("Aceptar");
        btnAceptarSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarSalirMenuActionPerformed(evt);
            }
        });

        btnActualizarStock.setBackground(new java.awt.Color(75, 90, 228));
        btnActualizarStock.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnActualizarStock.setForeground(new java.awt.Color(225, 225, 246));
        btnActualizarStock.setText("Actualizar stock");
        btnActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarStockActionPerformed(evt);
            }
        });

        btnRegresarRegistroIngrediente.setBackground(new java.awt.Color(51, 51, 51));
        btnRegresarRegistroIngrediente.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnRegresarRegistroIngrediente.setForeground(new java.awt.Color(225, 225, 246));
        btnRegresarRegistroIngrediente.setText("Volver a registro");
        btnRegresarRegistroIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarRegistroIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(btnAceptarSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnRegresarRegistroIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnActualizarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarRegistroIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlLabel.setBackground(new java.awt.Color(225, 225, 246));

        jLabel1.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 90, 228));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Se ha registrado el ingrediente.");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlLabelLayout = new javax.swing.GroupLayout(pnlLabel);
        pnlLabel.setLayout(pnlLabelLayout);
        pnlLabelLayout.setHorizontalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        pnlLabelLayout.setVerticalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlLabel, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAceptarSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarSalirMenuActionPerformed
        dispose();
        MenuPrincipalJFrame menu = new MenuPrincipalJFrame();
        menu.setVisible(true);
    }//GEN-LAST:event_btnAceptarSalirMenuActionPerformed

    private void btnActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarStockActionPerformed
        dispose();
        iIngredientesBO ingredientesBO = FabricaObjetoNegocio.crearIngredienteBO();
        CU3_ActualizarStock actualizarStockPantala = new CU3_ActualizarStock(ingredientesBO);
        actualizarStockPantala.setVisible(true);
    }//GEN-LAST:event_btnActualizarStockActionPerformed

    private void btnRegresarRegistroIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarRegistroIngredienteActionPerformed
        dispose();
        iIngredientesBO ingredientesBO = FabricaObjetoNegocio.crearIngredienteBO();
        CU3_RegistrarIngrediente registrarIngredientePantalla = new CU3_RegistrarIngrediente(ingredientesBO);
        registrarIngredientePantalla.setVisible(true);
    }//GEN-LAST:event_btnRegresarRegistroIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CU3_PantallaRegistroExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CU3_PantallaRegistroExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CU3_PantallaRegistroExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CU3_PantallaRegistroExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new CU3_RegistrarIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SeleccionUnidadMedida;
    private javax.swing.JButton btnAceptarSalirMenu;
    private javax.swing.JButton btnActualizarStock;
    private javax.swing.JButton btnRegresarRegistroIngrediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlLabel;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
