/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restauranteitson_PresentacionCU3_GestionIngredientes;

import restauranteitson_BusinessLogic_Fabrica.FabricaObjetoNegocio;
import restauranteitson_BusinessLogic_Interfaces.iIngredientesBO;

/**
 *
 * @author abrilislas
 */
public class MenuCU3_GestionIngredientes extends javax.swing.JFrame {

    /**
     * Creates new form MenuCU3_GestionIngredientes
     */
    iIngredientesBO ingredientesBO;
    
    public MenuCU3_GestionIngredientes() {
        initComponents();
        iIngredientesBO ingredientesBO = FabricaObjetoNegocio.crearIngredienteBO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrarNuevoIngrediente = new javax.swing.JButton();
        btnActualizarInventario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(854, 542));

        pnlRoot.setBackground(new java.awt.Color(225, 225, 246));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlLabel.setBackground(new java.awt.Color(225, 225, 246));

        jLabel1.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 90, 228));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de ingredientes");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlLabelLayout = new javax.swing.GroupLayout(pnlLabel);
        pnlLabel.setLayout(pnlLabelLayout);
        pnlLabelLayout.setHorizontalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))
        );
        pnlLabelLayout.setVerticalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnlRoot.add(pnlLabel, java.awt.BorderLayout.PAGE_START);

        pnlBotones.setBackground(new java.awt.Color(225, 225, 246));

        btnRegistrarNuevoIngrediente.setBackground(new java.awt.Color(75, 90, 228));
        btnRegistrarNuevoIngrediente.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnRegistrarNuevoIngrediente.setForeground(new java.awt.Color(225, 225, 246));
        btnRegistrarNuevoIngrediente.setText("Registrar un nuevo ingrediente");
        btnRegistrarNuevoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNuevoIngredienteActionPerformed(evt);
            }
        });

        btnActualizarInventario.setBackground(new java.awt.Color(51, 51, 51));
        btnActualizarInventario.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnActualizarInventario.setForeground(new java.awt.Color(225, 225, 246));
        btnActualizarInventario.setText("Actualizar inventario");
        btnActualizarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActualizarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarNuevoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnRegistrarNuevoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlBotones, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarNuevoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoIngredienteActionPerformed
        dispose();
        CU3_RegistrarIngrediente registrarIngredientePantalla = new CU3_RegistrarIngrediente(ingredientesBO);
        registrarIngredientePantalla.setVisible(true);
    }//GEN-LAST:event_btnRegistrarNuevoIngredienteActionPerformed

    private void btnActualizarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarInventarioActionPerformed
         dispose();
        CU3_ActualizarStock actualizarStockPantala = new CU3_ActualizarStock(ingredientesBO);
        actualizarStockPantala.setVisible(true);
    }//GEN-LAST:event_btnActualizarInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCU3_GestionIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCU3_GestionIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCU3_GestionIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCU3_GestionIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCU3_GestionIngredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarInventario;
    private javax.swing.JButton btnRegistrarNuevoIngrediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlLabel;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
