/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package restauranteitson_PresentacionCU1_Comandas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import restauranteitson_BusinessLogic_Exepciones.NegocioException;
import restauranteitson_BusinessLogic_Interfaces.IClientesBO;
import restauranteitson_PresentacionCU5_ManejoClientes.CU5_PantallaRegistroExitoso;
import restauranteitson_dominio.Cliente;
import restauranteitson_dtos.NuevoClienteDTO;

/**
 *
 * @author santi
 */
public class CU1_registrarCliente extends java.awt.Dialog {

    /**
     * Creates new form CU1_registrarCliente
     */
    private IClientesBO clientesBO;
    private Cliente cliente;
    
    public CU1_registrarCliente(java.awt.Frame parent, IClientesBO clientesBO) {
        super(parent, true);
        this.clientesBO = clientesBO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrarNuevoCliente = new javax.swing.JButton();
        btnSalirMenu = new javax.swing.JButton();
        pnlLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlFormulario = new javax.swing.JPanel();
        textField_NombreCliente = new javax.swing.JTextField();
        textField_TelefonoCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textField_EmailCliente = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnlRoot.setBackground(new java.awt.Color(225, 225, 246));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlBotones.setBackground(new java.awt.Color(225, 225, 246));

        btnRegistrarNuevoCliente.setBackground(new java.awt.Color(75, 90, 228));
        btnRegistrarNuevoCliente.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnRegistrarNuevoCliente.setForeground(new java.awt.Color(225, 225, 246));
        btnRegistrarNuevoCliente.setText("Registrar");
        btnRegistrarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNuevoClienteActionPerformed(evt);
            }
        });

        btnSalirMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnSalirMenu.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnSalirMenu.setForeground(new java.awt.Color(225, 225, 246));
        btnSalirMenu.setText("Salir");
        btnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnRegistrarNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlLabel.setBackground(new java.awt.Color(225, 225, 246));

        jLabel1.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 90, 228));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de cliente frecuente.");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlLabelLayout = new javax.swing.GroupLayout(pnlLabel);
        pnlLabel.setLayout(pnlLabelLayout);
        pnlLabelLayout.setHorizontalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
        );
        pnlLabelLayout.setVerticalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnlRoot.add(pnlLabel, java.awt.BorderLayout.PAGE_START);

        pnlFormulario.setBackground(new java.awt.Color(225, 225, 246));

        textField_NombreCliente.setForeground(new java.awt.Color(204, 204, 204));
        textField_NombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_NombreClienteActionPerformed(evt);
            }
        });

        textField_TelefonoCliente.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Hiragino Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Hiragino Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Número de telefóno");

        jLabel5.setFont(new java.awt.Font("Hiragino Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Correo electrónico");

        textField_EmailCliente.setForeground(new java.awt.Color(204, 204, 204));
        textField_EmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_EmailClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(textField_TelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(textField_EmailCliente)
                    .addComponent(textField_NombreCliente))
                .addGap(100, 218, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_TelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_EmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlFormulario, java.awt.BorderLayout.CENTER);

        add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private NuevoClienteDTO guardar(){
        // Extracción del contenido de los campos 
        String nombreCliente = textField_NombreCliente.getText();
        String telefonoCliente = textField_TelefonoCliente.getText();//recordar encriptar
        String emailCliente = textField_EmailCliente.getText();

        // Construccion del dto
        //String nombreCliente, String telefonoCliente, String CorreoCliente
        return new NuevoClienteDTO(nombreCliente, telefonoCliente, emailCliente);
    }
    
    private void btnRegistrarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoClienteActionPerformed
        //
        NuevoClienteDTO clienteDTO = guardar();

        try{
             System.out.println("primero aqui");
            this.cliente = clientesBO.registrar(clienteDTO);
            String mensajeExito = "Se registró exitosamente el cliente";
            System.out.println(cliente.getNombreCliente());
            System.out.println("aqui fijate");

            dispose();
        }catch(NegocioException e){
            JOptionPane.showMessageDialog(pnlFormulario, e);
            System.err.println("Hubo un error al intentar registrar al cliente");
        }
    }//GEN-LAST:event_btnRegistrarNuevoClienteActionPerformed

    public static Cliente mostrar(JFrame parent, IClientesBO clientesBO){
        CU1_registrarCliente u1_registrarCliente = new CU1_registrarCliente(parent,clientesBO);
        u1_registrarCliente.setVisible(true);
        return u1_registrarCliente.getCliente();
        
    }

    public Cliente getCliente() {
        return cliente;
    }
    
    private void btnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirMenuActionPerformed

    private void textField_NombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_NombreClienteActionPerformed
        // TODO add your handling code here:
        /*

        */
    }//GEN-LAST:event_textField_NombreClienteActionPerformed

    private void textField_EmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_EmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_EmailClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarNuevoCliente;
    private javax.swing.JButton btnSalirMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlLabel;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JTextField textField_EmailCliente;
    private javax.swing.JTextField textField_NombreCliente;
    private javax.swing.JTextField textField_TelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
