/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restauranteitson_PresentacionMENU;

import java.awt.Color;

/**
 *
 * @author abrilislas
 */
public class JFrameMenuPrincipalRestauranteITSON extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuPrincipalRestauranteITSON
     */
    public JFrameMenuPrincipalRestauranteITSON() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelControlRestaurante = new javax.swing.JLabel();
        btnComandasCU1 = new javax.swing.JButton();
        btnComandasCU2 = new javax.swing.JButton();
        btnComandasCU3 = new javax.swing.JButton();
        btnComandasCU4 = new javax.swing.JButton();
        btnComandasCU5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(53, 77, 240));

        jLabelControlRestaurante.setFont(new java.awt.Font("Tahoma", 1, 62)); // NOI18N
        jLabelControlRestaurante.setForeground(new java.awt.Color(51, 51, 255));
        jLabelControlRestaurante.setText("Control Restaurante");

        btnComandasCU1.setBackground(new java.awt.Color(51, 51, 51));
        btnComandasCU1.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 24)); // NOI18N
        btnComandasCU1.setForeground(new java.awt.Color(255, 255, 255));
        btnComandasCU1.setText("Comandas");
        btnComandasCU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandasCU1ActionPerformed(evt);
            }
        });

        btnComandasCU2.setBackground(new java.awt.Color(51, 51, 51));
        btnComandasCU2.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 24)); // NOI18N
        btnComandasCU2.setForeground(new java.awt.Color(255, 255, 255));
        btnComandasCU2.setText("Actualizar comandas");
        btnComandasCU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandasCU2ActionPerformed(evt);
            }
        });

        btnComandasCU3.setBackground(new java.awt.Color(51, 51, 51));
        btnComandasCU3.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 24)); // NOI18N
        btnComandasCU3.setForeground(new java.awt.Color(255, 255, 255));
        btnComandasCU3.setText("Gestión de ingredientes");
        btnComandasCU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandasCU3ActionPerformed(evt);
            }
        });

        btnComandasCU4.setBackground(new java.awt.Color(51, 51, 51));
        btnComandasCU4.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 24)); // NOI18N
        btnComandasCU4.setForeground(new java.awt.Color(255, 255, 255));
        btnComandasCU4.setText("Administrar productos");
        btnComandasCU4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandasCU4ActionPerformed(evt);
            }
        });

        btnComandasCU5.setBackground(new java.awt.Color(51, 51, 51));
        btnComandasCU5.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 24)); // NOI18N
        btnComandasCU5.setForeground(new java.awt.Color(255, 255, 255));
        btnComandasCU5.setText("Manejo de ingredientes");
        btnComandasCU5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandasCU5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelControlRestaurante)
                    .addComponent(btnComandasCU3, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComandasCU2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComandasCU1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComandasCU4, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComandasCU5, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabelControlRestaurante)
                .addGap(68, 68, 68)
                .addComponent(btnComandasCU1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComandasCU2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComandasCU3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComandasCU4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComandasCU5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComandasCU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasCU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComandasCU1ActionPerformed

    private void btnComandasCU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasCU2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComandasCU2ActionPerformed

    private void btnComandasCU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasCU3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComandasCU3ActionPerformed

    private void btnComandasCU4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasCU4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComandasCU4ActionPerformed

    private void btnComandasCU5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasCU5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComandasCU5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipalRestauranteITSON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipalRestauranteITSON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipalRestauranteITSON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipalRestauranteITSON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuPrincipalRestauranteITSON().setVisible(true);
          
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComandasCU1;
    private javax.swing.JButton btnComandasCU2;
    private javax.swing.JButton btnComandasCU3;
    private javax.swing.JButton btnComandasCU4;
    private javax.swing.JButton btnComandasCU5;
    private javax.swing.JLabel jLabelControlRestaurante;
    // End of variables declaration//GEN-END:variables
}
